### ISSUE TITLE
Bundle Transaction Data Items don't return from GraphQL query

### ISSUE THREAD

**Issue by jim-toth** [textury/arlocal#75] opened 2022-03-04 04:00 UTC
Getting this error back from the `/graphql` endpoint when searching for transactions that were posted as bundled data items:

```
{
    "errors": [
        {
            "message": "Cannot return null for non-nullable field Transaction.anchor.",
            "locations": [{ "line": 37, "column": 7 }],
            "path": ["transactions", "edges", 0, "node", "anchor"],
            "extensions": { "code": "INTERNAL_SERVER_ERROR" }
        }
    ],
    "data": null
}
```

Investigating the SQLite DB shows that these data item transactions are being inserted with `last_tx` value of `NULL`.  This is because data items don't have that field.

My guess is that it should be inserting empty string instead, like other tx that don't have a value for `last_tx`

**Comment by kouraf** [comment] 2022-03-04 09:22
Hello @jim-toth  thanks for reporting, can please share a code snippet to reproduce the error.

**Comment by fuadop** [comment] 2022-03-04 10:17
Hey @kouraf , I think can you check out his PR. The issue is a graphql validation issue.

**Comment by jim-toth** [comment] 2022-03-04 10:23
> Hello @jim-toth thanks for reporting, can please share a code snippet to reproduce the error.

Well, it's a bit complicated, but I'm posting an ANS-104 bundle (hand crafted, in the browser 🤣) that I can confirm works properly, except when a GQL query includes a data item tx no results will return due to the error in OP.

**Comment by jim-toth** [comment] 2022-03-04 10:30
Perhaps worth mentioning, afaik normal tx have `last_tx` explicitly set to empty string if no anchor is available, which is why it probably slipped through

**Comment by fuadop** [comment] 2022-03-04 13:36
Hey @jim-toth, a new version has been released with your change.

**Comment by cedriking** [comment] 2022-03-04 13:53
Hey @jim-toth thank you for looking into this! Version 1.1.24 has your fix added 🙌🏼

**Closed by cedriking** 2022-03-04 13:53 UTC
